import * as XLSX from "xlsx";
import {
  LpProblem,
  LpSolution,
  TransportationProblem,
  TransportationSolution,
  CpmSolution,
} from "./types";

export function generateLatexReport(
  module: string,
  problem: any,
  solution: any
): string {
  if (module === "linear-programming") {
    const lp = problem as LpProblem;
    const sol = solution as LpSolution;
    return `% Linear Programming Formulation & Optimal Solution
\\documentclass{article}
\\usepackage{amsmath, amssymb}

\\begin{document}
\\title{Linear Programming Optimization Report}
\\author{Generated by torsz}
\\maketitle

\\section{Mathematical Formulation}
\\begin{align*}
\\text{${lp.objective === "max" ? "Maximize" : "Minimize"}} \\quad & Z = ${lp.objectiveCoefficients
      .map((c, i) => `${c} x_{${i + 1}}`)
      .join(" + ")} \\\\
\\text{subject to} \\quad
${lp.constraints
  .map(
    (c) =>
      `& ${c.coefficients.map((v, i) => `${v} x_{${i + 1}}`).join(" + ")} ${
        c.operator === "<=" ? "\\le" : c.operator === ">=" ? "\\ge" : "="
      } ${c.rhs} \\\\`
  )
  .join("\n")}
& x_1, x_2 \\ge 0
\\end{align*}

\\section{Optimal Solution}
\\begin{itemize}
  \\item \\textbf{Optimal Objective Value ($Z^*$):} $${sol.objectiveValue}$
  \\item \\textbf{Optimal Variable Allocation:}
    ${sol.variableValues.map((v) => `$${v.name}^* = ${v.value}$`).join(", ")}
\\end{itemize}

\\end{document}`;
  }

  if (module === "transportation-assignment") {
    const trans = problem as TransportationProblem;
    const sol = solution as TransportationSolution;
    return `% Transportation Model Formulation & Solution (VAM)
\\documentclass{article}
\\usepackage{amsmath}

\\begin{document}
\\title{Transportation Shipping Optimization Report}
\\author{Generated by torsz}
\\maketitle

\\section{Problem Specification}
Total Supply: $${trans.supply.reduce((a, b) => a + b, 0)}$, Total Demand: $${trans.demand.reduce((a, b) => a + b, 0)}$.

\\section{Optimal Distribution Cost}
\\textbf{Total Minimum Shipping Cost:} $\\$${sol.totalCost.toLocaleString()}$

\\end{document}`;
  }

  return `% Operations Research Model Report
\\documentclass{article}
\\usepackage{amsmath}
\\begin{document}
\\title{Operations Research Solution Report}
\\author{Generated by torsz}
\\maketitle
\\section{Results}
Optimal Solution Metric: ${JSON.stringify(solution, null, 2)}
\\end{document}`;
}

export function exportSolutionToExcel(
  module: string,
  problem: any,
  solution: any
): void {
  const wb = XLSX.utils.book_new();

  if (module === "transportation-assignment" && problem?.sources && solution?.allocations) {
    const trans = problem as TransportationProblem;
    const sol = solution as TransportationSolution;

    const data: (string | number)[][] = [
      ["Transportation Optimization Model (VAM)"],
      [""],
      ["Source \\ Destination", ...trans.destinations, "Supply"],
      ...trans.sources.map((s, r) => [
        s,
        ...trans.destinations.map((_, c) => trans.costs[r][c]),
        trans.supply[r],
      ]),
      ["Demand", ...trans.demand, trans.supply.reduce((a, b) => a + b, 0)],
      [""],
      ["Optimal Shipping Allocation Plan"],
      ["From \\ To", ...trans.destinations],
      ...trans.sources.map((s, r) => [
        s,
        ...trans.destinations.map((_, c) => sol.allocations[r]?.[c] || 0),
      ]),
      [""],
      ["Total Minimum Cost ($)", sol.totalCost],
    ];

    const ws = XLSX.utils.aoa_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, ws, "Transportation_Solution");
    XLSX.writeFile(wb, "torsz_transportation_model.xlsx");
    return;
  }

  if (module === "project-planning" && solution?.activities) {
    const cpmSol = solution as CpmSolution;
    const data: (string | number)[][] = [
      ["Project Planning Schedule (CPM / PERT)"],
      ["Total Duration (weeks)", cpmSol.projectDuration],
      ["Critical Path", cpmSol.criticalPath.join(" -> ")],
      [""],
      ["Activity ID", "Duration", "Early Start", "Early Finish", "Late Start", "Late Finish", "Slack Float", "Critical?"],
      ...cpmSol.activities.map((a) => [
        a.id,
        a.duration,
        a.earlyStart,
        a.earlyFinish,
        a.lateStart,
        a.lateFinish,
        a.slack,
        a.isCritical ? "YES" : "NO",
      ]),
    ];

    const ws = XLSX.utils.aoa_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, ws, "CPM_Schedule");
    XLSX.writeFile(wb, "torsz_cpm_project_schedule.xlsx");
    return;
  }

  // Generic fallback worksheet
  const genericData = [
    ["Module", module],
    ["Problem", JSON.stringify(problem)],
    ["Solution", JSON.stringify(solution)],
  ];
  const ws = XLSX.utils.aoa_to_sheet(genericData);
  XLSX.utils.book_append_sheet(wb, ws, "OR_Solution");
  XLSX.writeFile(wb, `torsz_${module}_solution.xlsx`);
}

export function printExecutiveReport(
  moduleName: string,
  htmlContent: string
): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>torsz — ${moduleName} Executive Report</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #141413; background: #fff; }
          h1 { font-family: Georgia, serif; font-size: 26px; border-bottom: 2px solid #cc785c; padding-bottom: 8px; color: #141413; }
          h2 { font-size: 18px; margin-top: 24px; color: #3d3d3a; }
          table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px; }
          th, td { border: 1px solid #e6dfd8; padding: 8px 12px; text-align: left; }
          th { background-color: #f5f0e8; font-weight: 600; }
          .highlight { background-color: rgba(204, 120, 92, 0.1); font-weight: bold; color: #a9583e; }
          .footer { margin-top: 40px; font-size: 11px; color: #8e8b82; border-top: 1px solid #e6dfd8; padding-top: 8px; }
        </style>
      </head>
      <body>
        <h1>${moduleName} — Executive Briefing</h1>
        ${htmlContent}
        <div class="footer">Generated by torsz Optimization Suite • Verified Mathematical Models</div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}
